version: "3"

services:
  mariadb:
    image: wodby/mariadb:10-3.3.13
    container_name: "lessons910_mariadb"
    ports:
      - 3306:3306
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: answer
      MYSQL_USER: user
      MYSQL_PASSWORD: user